services:
    php:
        wait: 1h
        image: ${APP_NAME}_php
        build: .docker/php
        volumes:
            /.composer: ~
            app: /usr/src/app
            .whaler/php/run.sh: /.php/run.sh

    nginx:
        web: 80
        #ssl: 8443 send-proxy
        image: ${APP_NAME}_nginx
        build: .docker/nginx
        volumes:
            app/: /usr/src/app
            .whaler/nginx/conf.d: /etc/nginx/conf.d
            #.whaler/nginx/ssl: /etc/nginx/ssl
